$DRIVE = (Get-Location).Drive.Name + ":"

$env:PACKAGE_DIR = "$DRIVE\system\package"
$env:SOFTWARE_YAML = "$DRIVE\system\config\software.yaml"
$env:JUNCTIONS_JSON = "$DRIVE\system\config\junctions.json"
$env:APPS_DIR = "$DRIVE\system\software\apps"
$env:GAMES_DIR = "$DRIVE\system\software\games"
$env:APPS_SHORTCUTS_DIR = "$DRIVE\apps"
$env:GAMES_SHORTCUTS_DIR = "$DRIVE\games"
$env:PS_SCRIPTS_DIR = "$DRIVE\system\scripts\ps"
$env:LINK_PS = "$env:PS_SCRIPTS_DIR\link.ps1"

Write-Host "Environment variables initialized:"
Write-Host "PACKAGE_DIR = $env:PACKAGE_DIR"
Write-Host "SOFTWARE_YAML = $env:SOFTWARE_YAML"
Write-Host "JUNCTIONS_JSON = $env:JUNCTIONS_JSON"
Write-Host "APPS_DIR = $env:APPS_DIR"
Write-Host "GAMES_DIR = $env:GAMES_DIR"
Write-Host "APPS_SHORTCUTS_DIR = $env:APPS_SHORTCUTS_DIR"
Write-Host "GAMES_SHORTCUTS_DIR = $env:GAMES_SHORTCUTS_DIR"
Write-Host "PS_SCRIPTS_DIR = $env:PS_SCRIPTS_DIR"
Write-Host "LINK_PS = $env:LINK_PS"
